### ISSUE TITLE
Fails tests with Carp 1.24 or lower

### ISSUE THREAD

**Issue by andk** [ap/Bencode#4]
As per subject. Sample fail report: http://www.cpantesters.org/cpan/report/87505520

Analysis: http://analysis.cpantesters.org/reports_by_field?SUBMIT_xxx=Submit&distv=Bencode-1.500&field=mod%3ACarp

Cap 1.25 introduced the dot at the end of the message. So either Carp 1.25 is a requirement or the test needs to be rewritten as a like().

Best,

**Comment by ap** [comment]
Hey, thanks for the report 😊  I’m aware, CPAN Testers has been mailing me.

As for the fix, I’m considering option 3: not using Carp at all.

**Comment by ap** [comment]
This should be fixed by 7c6a13b74a2a1b0eda649e9a13b9a61f60ca6ddb.

**Comment by ap** [comment]
Matrix is green. 😊
